###############
GPU: [0]
PORT: 4567

MODEL:
  NAME: UNet
  MODE: small_baseline   #
  ARGS:
    inp_channels: 3
    out_channels: 3
    channel: 36
    win_size: [32,32,32]
    heads: [1,2,4]
    depth: [4,4,16]
    bias: false

TRAIN:
  TOTAL_EPOCHS: 2400
  BATCH_SIZE: 1

  PRINT_FRE: 160           ## iter frequency of print
  SAVE: 0                 ## when to start save checkpoints
  SAVE_FRE:  100           ## epoch frequency of save checkpoints
  VAL: 0                  ## when to val
  VAL_FRE:  1          ## epoch frequency of val
  SAVE_IMG: false         ## val nseed save images?
  
  RESUME:    false        ## resume? true or false
  PRETRAIN_MODEL: model_latest.pth       ## pretrain_model: latested or epoch_num
  TRAIN_PS:  256          ## patchsize of train
  VAL_PS:    ~            ## patchsize of val

PATH:
  TRAIN_DATASET: '/media/ubutu/755546c0-dea6-4996-b0a4-510af8d67bde/GOPRO/train'
  VAL_DATASET:  '/media/ubutu/755546c0-dea6-4996-b0a4-510af8d67bde/GOPRO/test'

# Optimization arguments.
OPTIM:
    lr: !!float 
    betas: [0.9, 0.999]

#schedual arguments.
SCHE:
  T_max: 
  eta_min: !!float 1e-6


WARM_UP:
  use_warm_up: false
  warm_up_lr: !!float 2e-4
  warm_up_epoch: 1

